spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: pas
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
        
---

spring:
  profiles: dev

---
spring:
  profiles: test
  datasource:
    schema: classpath:/schema-test.sql
    data: classpath:/data-test.sql
